# Default initial positions for mycobot_280's ros2_control fake system

initial_positions:
  base_link_to_link1: 0
  link1_to_link2: 0
  link2_to_link3: 0
  link3_to_link4: 0
  link4_to_link5: 0
  link5_to_link5_flange: 0